---
title: "Correlation between sales of craft beer styles and reviews"
author: "Anthony Kutovoy"
date: "December 7, 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(latexpdf)
library(stringr)
beer_reviews <- read.csv("beer_reviews.csv")
unique_reviews <- distinct(beer_reviews, review_profilename, .keep_all = T)
attach(unique_reviews)
unique_reviews <- unique_reviews[order(review_time),]
unique_reviews <- subset(unique_reviews,  review_time > 1199145660, c(review_profilename, review_time, review_overall, beer_style))

ipas <- unique_reviews %>% filter(str_detect(beer_style, "IPA"))
sours <- unique_reviews %>% filter(str_detect(beer_style, "Sour|Gose|Wild|Fruit"))
light <- unique_reviews %>% filter(str_detect(beer_style, "Golden|Blonde|Pilsner"))
stouts <- unique_reviews %>% filter(str_detect(beer_style, "Stout|Black|Porter"))

t_ipas <- t.test(ipas$review_overall[ipas$review_time>1293840060], ipas$review_overall[ipas$review_time<1293840060], mu=0, alternative = "two.sided")
t_sours <- t.test(sours$review_overall[sours$review_time>1293840060], sours$review_overall[sours$review_time<1293840060], mu=0, alternative = "two.sided")
t_light <- t.test(light$review_overall[light$review_time>1293840060], light$review_overall[light$review_time<1293840060], mu=0, alternative = "two.sided")
t_stouts <- t.test(stouts$review_overall[stouts$review_time>1293840060], stouts$review_overall[stouts$review_time<1293840060], mu=0, alternative = "two.sided")
```

## Introduction

In modern history, Beer has been a big business worldwide and especially in the United states. Here it is manufactured by more than 3,000 breweries, which range in size from industry giants to brew pubs and microbreweries. The United States produced 196 million barrels (23.0 GL) of beer in 2012, and consumes roughly 28 US gallons (110 L) of beer per capita annually in USA (citation coming).

Although lager & sales from large breweries have preserved their dominance for 100 years, since the 1990s their market share has been steadily decreasing due to emergence of craft and particularly IPA-style beers, which have been leading craft sales figures for 2 decades. In his article [What's the next IPA?](https://www.brewersassociation.org/insights/the-next-ipa/) , Bart Watson examines rapid growth in the IPA share within the craft industry between 2008 and 2015. I seek to investigate whether craft beer rating trends during the slower growth periods for top-selling styles are correlated with future accelerating growth in sales.

